project_id = "ltgxvskqotbuclrinhej"

[functions.cleanup-old-events]
verify_jwt = false

[functions.scrape-instagram]
verify_jwt = false

[functions.enrich-event]
verify_jwt = false

[functions.enrich-post-ocr]
verify_jwt = false

[functions.geocode-location]
verify_jwt = false

[functions.suggest-location-corrections]
verify_jwt = true

[functions.publish-event]
verify_jwt = true

[functions.save-location-correction]
verify_jwt = true
