/**
 * Database Migration Runner
 *
 * Runs Drizzle migrations against the PostgreSQL database.
 * Migrations are generated by `npm run db:generate` (drizzle-kit)
 * and stored in the `drizzle/` directory.
 *
 * ## Usage
 * ```bash
 * # Generate migrations from schema changes
 * cd server && npm run db:generate
 *
 * # Apply migrations
 * cd server && npm run db:migrate
 * ```
 *
 * ## How Drizzle Migrations Work
 *
 * 1. You modify `src/db/schema.ts`
 * 2. Run `drizzle-kit generate` → creates SQL migration files in `drizzle/`
 * 3. Run this script → applies pending migrations to PostgreSQL
 * 4. Drizzle tracks which migrations have been applied in a `__drizzle_migrations` table
 *
 * For development, you can also use `npm run db:push` which applies
 * schema changes directly without generating migration files (faster
 * iteration, but no migration history).
 */

import 'dotenv/config';
import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';

async function main() {
  if (!process.env.DATABASE_URL) {
    throw new Error('DATABASE_URL environment variable is required');
  }

  console.log('🔄 Running migrations...');

  const sql = postgres(process.env.DATABASE_URL, { max: 1 });
  const db = drizzle(sql);

  await migrate(db, { migrationsFolder: './drizzle' });

  console.log('✅ Migrations complete');
  await sql.end();
  process.exit(0);
}

main().catch((err) => {
  console.error('❌ Migration failed:', err);
  process.exit(1);
});
