-- Add index for faster lookups on pattern_suggestions status
CREATE INDEX IF NOT EXISTS idx_pattern_suggestions_status 
ON pattern_suggestions(status);

-- Add index for pattern_suggestions by pattern_type
CREATE INDEX IF NOT EXISTS idx_pattern_suggestions_type 
ON pattern_suggestions(pattern_type);

-- Add generated_pattern column to pattern_suggestions if it doesn't exist
ALTER TABLE pattern_suggestions 
ADD COLUMN IF NOT EXISTS generated_pattern TEXT;

-- Update the source check constraint to include 'ai_learned' value
-- First drop the existing constraint if it exists
DO $$ 
BEGIN
  ALTER TABLE extraction_patterns DROP CONSTRAINT IF EXISTS extraction_patterns_source_check;
EXCEPTION
  WHEN undefined_object THEN
    NULL;
END $$;

-- Add updated constraint with 'ai_learned' option
ALTER TABLE extraction_patterns 
ADD CONSTRAINT extraction_patterns_source_check 
CHECK (source IN ('default', 'learned', 'manual', 'ai_learned'));

-- Comment on the source column
COMMENT ON COLUMN extraction_patterns.source IS 'Pattern source: default (built-in), learned (from corrections), manual (user created), ai_learned (generated by AI from ground truth)';
