-- Add missing venues to known_venues table
-- INSERT INTO public.known_venues (name, address, city, lat, lng, aliases) VALUES
--   ('Jungle Base Cafe', 'Marikina City', 'Marikina', 14.6507, 121.1029, ARRAY['Jungle Base', 'JBC']),
--   ('Mercato Centrale', 'Bonifacio High Street, BGC', 'Taguig', 14.5513, 121.0503, ARRAY['Mercato']),
--   ('SMX Convention Center Aura', 'SM Aura Premier, BGC', 'Taguig', 14.5494, 121.0556, ARRAY['SMX Aura', 'SMXAura', 'SM Aura Convention']),
--   ('The Annex at SM Aura', 'SM Aura Premier, BGC', 'Taguig', 14.5494, 121.0556, ARRAY['Annex Atrium', 'SM Aura Annex', 'The Annex']),
--   ('Town Plaza BGC', 'Bonifacio Global City', 'Taguig', 14.5519, 121.0450, ARRAY['Town Plaza', 'BGC Town Plaza']),
--   ('Hungry Neighbors', 'Poblacion, Makati', 'Makati', 14.5649, 121.0300, ARRAY['Hungry Neighbors Poblacion']),
--   ('Newport Performing Arts Center', 'Newport City, Pasay', 'Pasay', 14.5101, 121.0297, ARRAY['Newport PAC', 'NPAT']),
--   ('Capilla de San Lorenzo', 'Intramuros, Manila', 'Manila', 14.5908, 120.9750, ARRAY['San Lorenzo Chapel', 'Capilla San Lorenzo']),
--   ('Drawing Room Manila', 'Makati City', 'Makati', 14.5547, 121.0244, ARRAY['Drawing Room', 'The Drawing Room']),
--   ('Bo''s Coffee', 'Multiple locations', 'Metro Manila', 14.5547, 121.0244, ARRAY['Bos Coffee', 'BosCoffee']),
--   ('HUB Make Lab', 'Makati City', 'Makati', 14.5623, 121.0269, ARRAY['Hub Makelab', 'Hub Make Lab Makati']),
--   ('Basement 1', 'Poblacion, Makati', 'Makati', 14.5649, 121.0310, ARRAY['Basement One', 'B1 Poblacion']),
--   ('The Balmori Chef''s Table', 'Makati City', 'Makati', 14.5547, 121.0244, ARRAY['Balmori', 'Balmori Chef Table']),
--   ('Sundeck Party Zhostel', 'Poblacion, Makati', 'Makati', 14.5649, 121.0305, ARRAY['Sundeck', 'Zhostel Sundeck', 'Sundeck Poblacion']),
--   ('Lost and Found Makati', 'Poblacion, Makati', 'Makati', 14.5649, 121.0295, ARRAY['Lost and Found', 'Lost & Found Makati']),
--   ('Corte', 'Poblacion, Makati', 'Makati', 14.5649, 121.0300, ARRAY['Corte Poblacion', 'Corte Makati']),
--   ('Z Hostel Rooftop', 'Poblacion, Makati', 'Makati', 14.5649, 121.0303, ARRAY['Z Hostel', 'Z Rooftop']),
--   ('Agimat Foraging Bar', 'Poblacion, Makati', 'Makati', 14.5649, 121.0298, ARRAY['Agimat', 'Agimat Bar']),
--   ('Pink Panda', 'Poblacion, Makati', 'Makati', 14.5649, 121.0308, ARRAY['Pink Panda Poblacion'])
-- -- ON CONFLICT (name) DO UPDATE SET
--   address = EXCLUDED.address,
--   city = EXCLUDED.city,
--   lat = EXCLUDED.lat,
--   lng = EXCLUDED.lng,
--   aliases = EXCLUDED.aliases,
--   updated_at = now();